// Generated by CoffeeScript 1.3.3
(function() {
  var clear, extend, fs, readJson;

  fs = require('fs');

  module.exports = function(file, interval) {
    var obj;
    obj = readJson(file);
    fs.watchFile(file, {
      persistent: true,
      interval: interval || 500
    }, function() {
      var ext;
      ext = readJson(file);
      clear(obj);
      return extend(obj, ext);
    });
    return obj;
  };

  readJson = function(file) {
    var data;
    data = fs.readFileSync(file, 'utf-8');
    try {
      return eval(data);
    } catch (e) {
      console.log('Cant\'t parse file `' + file('`'));
      return {};
    }
  };

  clear = function(obj) {
    var name, _results;
    if ('length' in obj && 'splice' in obj) {
      return obj.splice(0, obj.length);
    } else {
      _results = [];
      for (name in obj) {
        _results.push(delete obj[name]);
      }
      return _results;
    }
  };

  extend = function(obj, ext) {
    var name, _results;
    _results = [];
    for (name in ext) {
      _results.push(obj[name] = ext[name]);
    }
    return _results;
  };

}).call(this);
