// Generated by CoffeeScript 1.3.3
(function() {
  var clear, coffee, extend, fs, readJson;

  fs = require('fs');

  coffee = require('coffee-script');

  module.exports = function(file, interval, context, handler) {
    var obj;
    if (typeof context === 'function') {
      handler = context;
      context = void 0;
    }
    obj = readJson(file, context);
    if (handler) {
      obj = handler(obj) || obj;
    }
    fs.watchFile(file, {
      persistent: true,
      interval: interval || 500
    }, function() {
      var ext;
      ext = readJson(file, context);
      if (handler) {
        ext = handler(ext) || ext;
      }
      clear(obj);
      return extend(obj, ext);
    });
    return obj;
  };

  readJson = function(file, context) {
    var data, isCoffee;
    data = fs.readFileSync(file, 'utf-8');
    isCoffee = !!file.match(/\.coffee$/);
    try {
      return (function() {
        if (isCoffee) {
          return coffee["eval"]('(' + data + ')', {
            sandbox: context
          });
        } else {
          return eval(data);
        }
      }).call(context || global);
    } catch (e) {
      console.log('Cant\'t parse file `' + file + '`');
      return {};
    }
  };

  clear = function(obj) {
    var name, _results;
    if ('length' in obj && 'splice' in obj) {
      return obj.splice(0, obj.length);
    } else {
      _results = [];
      for (name in obj) {
        _results.push(delete obj[name]);
      }
      return _results;
    }
  };

  extend = function(obj, ext) {
    var name, _results;
    _results = [];
    for (name in ext) {
      _results.push(obj[name] = ext[name]);
    }
    return _results;
  };

}).call(this);
