// Generated by CoffeeScript 1.4.0
(function() {
  var arrFileCS, arrFileJS, completeTest, context, context2, exampleArrCS1, exampleArrCS2, exampleArrJS1, exampleArrJS2, exampleObjCS1, exampleObjCS2, exampleObjJS1, exampleObjJS2, fs, jsync, objFileCS, objFileJS, testArr1, testArr2, testArr3, testObj1, testObj2, testObj3;

  fs = require('fs');

  jsync = require('./jsync.js');

  testObj1 = function(obj) {
    return obj.prop === 'value' && Object.keys(obj).length === 3 && typeof obj.func === 'function';
  };

  testArr1 = function(arr) {
    return arr[0] === 'value' && arr.length === 3 && typeof arr[2] === 'function';
  };

  testObj2 = function(obj) {
    return obj.context === 'foo' && Object.keys(obj).length === 2 && typeof obj.func === 'function';
  };

  testArr2 = function(arr) {
    return arr[0] === 'foo' && arr.length === 2 && typeof arr[1] === 'function';
  };

  testObj3 = function(obj) {
    return obj.context === 'bar' && Object.keys(obj).length === 2 && typeof obj.func === 'function';
  };

  testArr3 = function(arr) {
    return arr[0] === 'bar' && arr.length === 2 && typeof arr[1] === 'function';
  };

  objFileJS = __dirname + '/example_obj.js';

  arrFileJS = __dirname + '/example_arr.js';

  objFileCS = __dirname + '/example_obj.coffee';

  arrFileCS = __dirname + '/example_arr.coffee';

  exampleArrCS1 = '["value", @prop, -> no]';

  exampleArrJS1 = "['value', this.prop, function() {return false;}]";

  exampleObjCS1 = "prop: 'value'\ncontext: this.prop\nfunc: -> no\n";

  exampleObjJS1 = "{\n	prop: 'value',\n	context: this.prop,\n	func: function() {return false;}\n}";

  exampleArrCS2 = '[@prop, -> no]';

  exampleArrJS2 = "[this.prop, function() {return false;}]";

  exampleObjCS2 = "context: this.prop\nfunc: -> no\n";

  exampleObjJS2 = "{\n	context: this.prop,\n	func: function() {return false;}\n}";

  context = {
    prop: 'foo'
  };

  context2 = {
    prop: 'bar'
  };

  module.exports = {
    read: {
      js: {
        obj: function(test) {
          var obj;
          fs.writeFileSync(objFileJS, exampleObjJS1, 'utf-8');
          obj = jsync.read(objFileJS);
          test.ok(testObj1(obj));
          return test.done();
        },
        arr: function(test) {
          var arr;
          fs.writeFileSync(arrFileJS, exampleArrJS1, 'utf-8');
          arr = jsync.read(arrFileJS);
          test.ok(testArr1(arr));
          return test.done();
        }
      },
      coffee: {
        obj: function(test) {
          var obj;
          fs.writeFileSync(objFileCS, exampleObjCS1, 'utf-8');
          obj = jsync.read(objFileCS);
          test.ok(testObj1(obj));
          return test.done();
        },
        arr: function(test) {
          var arr;
          fs.writeFileSync(arrFileCS, exampleArrCS1, 'utf-8');
          arr = jsync.read(arrFileCS);
          test.ok(testArr1(arr));
          return test.done();
        }
      }
    },
    syncAndHandle: {
      js: {
        obj: function(test) {
          var counter, obj;
          test.expect(3);
          counter = 0;
          obj = jsync(objFileJS, 50, context, function(err, obj) {
            if (counter === 2) {
              test.ok(true);
              return;
            }
            if (!counter) {
              counter++;
              return;
            }
            counter++;
            return test.ok(testObj2(obj), 'type 2-1: ' + obj);
          });
          setTimeout(function() {
            return fs.writeFile(objFileJS, exampleObjJS2, 'utf-8');
          }, 10);
          setTimeout(function() {
            return jsync.trigger(obj);
          }, 150);
          return setTimeout(function() {
            test.ok(testObj2(obj), 'type 2-2: ' + obj);
            jsync.cancel(obj);
            return test.done();
          }, 200);
        },
        arr: function(test) {
          var arr, counter;
          test.expect(3);
          counter = 0;
          arr = jsync(arrFileJS, 50, context, function(err, arr) {
            if (counter === 2) {
              test.ok(testArr3(arr), 'type 3-1: ' + arr);
              return;
            }
            if (!counter) {
              counter++;
              return;
            }
            counter++;
            return test.ok(testArr2(arr), 'type 2: ' + arr);
          });
          setTimeout(function() {
            return fs.writeFileSync(arrFileJS, exampleArrJS2, 'utf-8');
          }, 50);
          setTimeout(function() {
            return jsync.trigger(arr, context2);
          }, 150);
          return setTimeout(function() {
            test.ok(testArr3(arr), 'type 3-2: ' + arr);
            jsync.cancel(arr);
            return test.done();
          }, 200);
        }
      },
      coffee: {
        obj: function(test) {
          var counter, obj;
          test.expect(3);
          counter = 0;
          obj = jsync(objFileCS, 50, context, function(err, obj) {
            if (counter === 2) {
              test.ok(testObj3(obj), 'type 3-1: ' + obj);
              return;
            }
            if (!counter) {
              counter++;
              return;
            }
            counter++;
            return test.ok(testObj2(obj), 'type 2: ' + obj);
          });
          setTimeout(function() {
            return fs.writeFileSync(objFileCS, exampleObjCS2, 'utf-8');
          }, 50);
          setTimeout(function() {
            return jsync.trigger(obj, context2);
          }, 150);
          return setTimeout(function() {
            test.ok(testObj3(obj), 'type 3-2: ' + obj);
            jsync.cancel(obj);
            return test.done();
          }, 200);
        },
        arr: function(test) {
          var arr, counter;
          test.expect(3);
          counter = 0;
          arr = jsync(arrFileCS, 50, context, function(err, arr) {
            if (counter === 2) {
              test.ok(true);
              return;
            }
            if (!counter) {
              counter++;
              return;
            }
            counter++;
            return test.ok(testArr2(arr), 'type 2-1: ' + arr);
          });
          setTimeout(function() {
            return fs.writeFileSync(arrFileCS, exampleArrCS2, 'utf-8');
          }, 50);
          setTimeout(function() {
            return jsync.trigger(arr);
          }, 150);
          return setTimeout(function() {
            test.ok(testArr2(arr), 'type 2-2: ' + arr);
            jsync.cancel(arr);
            return test.done();
          }, 200);
        }
      }
    },
    save: {
      js: {
        arr: function(test) {
          var arr, counter;
          test.expect(3);
          counter = 0;
          fs.writeFileSync(arrFileJS, exampleArrJS1, 'utf-8');
          arr = jsync(arrFileJS, 50, context, function(err, arr) {
            if (counter) {
              return;
            }
            counter++;
            return test.ok(testArr1(arr), 'type 1: ' + arr);
          });
          setTimeout(function() {
            var arr2;
            arr.splice(0, 2, 'bar');
            jsync.save(arr);
            jsync.save(arr, arrFileJS + '.temp.js');
            arr2 = jsync.read(arrFileJS + '.temp.js');
            return test.ok(testArr3(arr2), 'type 3-1: ' + arr2);
          }, 150);
          return setTimeout(function() {
            test.ok(testArr3(arr), 'type 3-2: ' + arr);
            jsync.cancel(arr);
            return test.done();
          }, 200);
        }
      },
      coffee: {
        obj: function(test) {
          var counter, obj;
          test.expect(3);
          counter = 0;
          fs.writeFileSync(objFileCS, exampleObjCS1, 'utf-8');
          obj = jsync(objFileCS, 50, context, function(err, obj) {
            if (counter) {
              return;
            }
            counter++;
            return test.ok(testObj1(obj), 'type 1: ' + obj);
          });
          setTimeout(function() {
            return fs.writeFileSync(objFileCS, exampleObjCS2, 'utf-8');
          }, 50);
          setTimeout(function() {
            var obj2;
            delete obj.prop;
            obj.context = 'bar';
            jsync.save(obj);
            jsync.save(obj, objFileCS + '.temp.coffee');
            obj2 = jsync.read(objFileCS + '.temp.coffee');
            return test.ok(testObj3(obj2), 'type 3-1: ' + obj2);
          }, 150);
          return setTimeout(function() {
            test.ok(testObj3(obj), 'type 3-2: ' + obj);
            jsync.cancel(obj);
            test.done();
            return completeTest();
          }, 200);
        }
      }
    }
  };

  completeTest = function() {
    fs.unlinkSync(objFileJS);
    fs.unlinkSync(arrFileCS);
    fs.unlinkSync(objFileCS);
    fs.unlinkSync(arrFileJS);
    fs.unlinkSync(objFileCS + '.temp.coffee');
    return fs.unlinkSync(arrFileJS + '.temp.js');
  };

}).call(this);
